name: Publish NuGet Packages

on:
  release:
    types: [published]
    
permissions:
  packages: write
  contents: read  
  
jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: .
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0  

      - name: Download NuGet Packages from Release
        run: |
            Write-Host "GITHUB_REF: '$($env:GITHUB_REF)'"
            $prefix = "refs/tags/"
            $name = $($env:GITHUB_REF).Substring($prefix.Length)
            Write-Host "name: '$name'"
            gh release download $name --repo siemens/sourcegrid --pattern '*.nupkg' --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to github packages
        run: |          
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://api.nuget.org/v3/index.json"
        env:
            USERNAME: ${{ secrets.USERNAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
